run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 10m

output:
  # Print linter name in the end of issue text.
  # Default: true
  print-linter-name: true
  print-issued-lines: true

linters-settings:
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # See the https://github.com/polyfloyd/go-errorlint for caveats.
    # Default: true
    errorf: true
    # Permit more than 1 %w verb, valid per Go 1.20 (Requires errorf:true)
    # Default: true
    errorf-multi: false
    # Check for plain type assertions and type switches.
    # Default: true
    asserts: true
    # Check for plain error comparisons.
    # Default: true
    comparison: true
linters:
  enable:
    - errorlint
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused