services:
  redis:
    image: redis
    entrypoint:
    - "/usr/local/bin/redis-server"
    - --requirepass ${REDIS_PASS}
    env_file:
      deploy/.env
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
  pg:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
    env_file:
      deploy/.env
    ports:
    - "${PG_PORT}:${PG_PORT}"
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    env_file:
      deploy/.env
    ports:
    - "${MONGO_PORT}:${MONGO_PORT}"
  gitea:
    build:
      context: https://github.com/openmerlin/gitea.git
      dockerfile: Dockerfile.rootless_cdn
      args:
        GITEA_VERSION: 1.21.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/app.ini:/etc/gitea/app.ini
    env_file:
      deploy/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
    - "${GITEA_PORT}:${GITEA_PORT}"
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
    - redis
    - db
    - gitea
    command:
      - --config-file
      - /home/modelfoundry/config.yml
      - --enable_debug
      - "true"
      - --rm-cfg
      - "false"
      - --port
      - ${SERVER_PORT}
    volumes:
      - ./deploy/config.yml:/home/modelfoundry/config.yml:ro
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      deploy/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${SERVER_PORT}/api/swagger/index.html"]
      interval: 30s
      timeout: 5s
      retries: 5