organization:
  invite_expiry: 1209600

authing:
  app_id: ""
  secret: ""
  endpoint: ""

gitea:
  url: ""
  token: ""

mongodb:
  db_conn: ""
  db_name: "merlin"
  db_cert: ""
  collections:
    user: user
    session: session
    organization: organization
    member: member
    token: token

permission:
  permissions:
    - object_type: member
      rules:
        - role: admin
          operation:
          - write
          - create
          - read
          - delete
        - role: contributor
          operation:
          - read
        - role: write
          operation:
          - read
        - role: read
          operation:
          - read
    - object_type: invite
      rules:
        - role: admin
          operation:
          - write
          - create
          - read
          - delete
    - object_type: organization
      rules:
        - role: admin
          operation:
          - write
          - create
          - read
          - delete
        - role: contributor
          operation:
          - read
        - role: write
          operation:
          - read
        - role: read
          operation:
          - read
    - object_type: model
      rules:
        - role: admin
          operation:
          - write
          - create
          - read
          - delete
        - role: contributor
          operation:
          - write
          - create
          - read
          - delete
        - role: write
          operation:
          - write
          - read
        - role: read
          operation:
          - read

model:
  tables:
    model: ""

redis:
  address: ""
  password: ""
  db_cert: ""
  db: 0

api:
  # this is a 32 byte length key encoded by base64
  # which is generated by `openssl rand -base64 32`
  token_key: ""
  token_expiry: 28800
  encryption_key: ""
  encryption_key_csrf: ""

user:
  max_bio_length: 200
  avatar_url:
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-3.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-2.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-1.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-4.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_01.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_02.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_03.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_04.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_05.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_06.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_07.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_08.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-1.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-2.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-3.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-4.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-1.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-2.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-3.png"
  - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-4.png"

primitive:
  licenses:
  - "apache-2.0"
  - "mit"
  - "cc-by-sa-3.0"
  - "afl-3.0"
  - "cc-by-sa-4.0"
  - "lgpl-3.0"
  - "lgpl-lr"
  - "cc-by-nc-3.0"
  - "bsd-2-clause"
  - "ecl-2.0"
  - "cc-by-nc-sa-4.0"
  - "cc-by-nc-4.0"
  - "gpl-3.0"
  - "cc0-1.0"
  - "cc"
  - "bsd-3-clause"
  - "agpl-3.0"
  - "wtfpl"
  - "artistic-2.0"
  - "postgresql"
  - "gpl-2.0"
  - "isc"
  - "eupl-1.1"
  - "pddl"
  - "bsd-3-clause-clear"
  - "mpl-2.0"
  - "odbl-1.0"
  - "cc-by-4.0"

postgresql:
  host: ""
  user: ""
  pwd: ""
  name: ""
  port: 5432
