services:
  redis:
    image: redis
    entrypoint:
    - "/usr/local/bin/redis-server"
    - --requirepass merlin
  pg:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: gitea
      POSTGRES_USER: gitea
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: merlin
      MONGO_INITDB_ROOT_PASSWORD: merlin
  gitea:
    build:
      context: https://github.com/openmerlin/gitea.git
      dockerfile: Dockerfile.rootless_cdn
      args:
        GITEA_VERSION: 1.21.1

    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
  server:
    build: .
    depends_on:
    - redis
    - db
    - gitea
    entrypoint:
      - /home/openmerlin/merlin-server
      - --config-file
      - /home/openmerlin/config.yml
      - --enable_debug
      - "true"
      - --rm-cfg
      - "false"
    volumes:
      - ./compose-config.yml:/home/openmerlin/config.yml:ro
    ports:
    - "8888:8888"

volumes:
  gitea: