services:
  vault:
    image: hashicorp/vault
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201'
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 8201 > /dev/null; if [ 0 != $? ]; then exit 1; fi;"]
      interval: 5s
      timeout: 30s
      retries: 10
    command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"
    networks:
      network:
        ipv4_address: 10.5.0.2
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server 127.0.0.1:9092"]
      interval: 5s
      timeout: 30s
      retries: 10
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      network:
        ipv4_address: 10.5.0.3
  redis:
    image: redis
    entrypoint:
    - "/usr/local/bin/redis-server"
    - --requirepass ${REDIS_PASS}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASS} ping"]
      interval: 5s
      timeout: 30s
      retries: 10
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      network:
        ipv4_address: 10.5.0.4
  pg:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${GITEA_DB_NAME}"]
      interval: 5s
      timeout: 30s
      retries: 10
    ports:
    - "${PG_PORT}:${PG_PORT}"
    networks:
      network:
        ipv4_address: 10.5.0.5
  gitea:
    build:
      context: https://github.com/openmerlin/gitea.git#main
      dockerfile: Dockerfile.rootless_cdn
      args:
        GITEA_VERSION: 1.21.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - KAFKA_ADDR=10.5.0.3:9092
      - KAFKA_VER=2.1.0
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/app.ini:/etc/gitea/app.ini
      - ./tests/gitea-deploy/options:/var/lib/gitea/custom/options
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000"]
      interval: 5s
      timeout: 30s
      retries: 10
    ports:
    - "${GITEA_PORT}:${GITEA_PORT}"
    networks:
      network:
        ipv4_address: 10.5.0.6
    depends_on:
      kafka:
        condition: service_healthy
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      vault:
        condition: service_healthy
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: debug
        GH_USER: ${GH_USER}
        GH_TOKEN: ${GH_TOKEN}
    depends_on:
      kafka:
        condition: service_healthy
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      gitea:
        condition: service_healthy
    command:
      - --config-file
      - /home/modelfoundry/config.yml
      - --enable_debug
      - "true"
      - --rm-cfg
      - "false"
      - --port
      - ${SERVER_PORT}
    volumes:
      - ./deploy/config.yml:/home/modelfoundry/config.yml:ro
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${SERVER_PORT}/internal/heartbeat"]
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      network:
        ipv4_address: 10.5.0.7

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1