// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1//request": {
            "delete": {
                "description": "Revoke member request of the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Revoke member request of the organization",
                "parameters": [
                    {
                        "description": "body of the member request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.OrgRevokeMemberReqRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "organization name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.ApproveDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            }
        },
        "/v1/account/{name}": {
            "get": {
                "description": "get organization or user info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Get one organization or user info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/v1/invite": {
            "get": {
                "description": "List invitation of the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "List invitation of the organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organization name",
                        "name": "org",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "invitee name",
                        "name": "invitee",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "inviter name",
                        "name": "inviter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "invitation status, can be: pending/approved/rejected",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page index",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.ApproveDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            },
            "put": {
                "description": "Accept invite of the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Accept invite of the organization",
                "parameters": [
                    {
                        "description": "body of the invitation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.OrgAcceptMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.ApproveDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            },
            "post": {
                "description": "Send invitation to a user to join the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Invite a user to be a member of the organization",
                "parameters": [
                    {
                        "description": "body of the invitation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.OrgInviteMemberRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/app.OrganizationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            },
            "delete": {
                "description": "Revoke invitation of the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Revoke invitation of the organization",
                "parameters": [
                    {
                        "description": "body of the invitation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.OrgRevokeInviteRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "organization name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.ApproveDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "get": {
                "description": "callback of authentication by authing",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "authing code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "redirect uri",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_openmerlin_merlin-server_user_app.UserDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "duplicate_creating"
                        }
                    }
                }
            }
        },
        "/v1/logout": {
            "get": {
                "description": "get info of login",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.SessionDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/v1/model": {
            "get": {
                "description": "list global public model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelWeb"
                ],
                "summary": "ListGlobal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of model",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "task label",
                        "name": "task",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "other labels, separate multiple each ones with commas",
                        "name": "others",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "license label",
                        "name": "license",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "framework labels, separate multiple each ones with commas",
                        "name": "frameworks",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "whether to calculate the total",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort types: most_likes, alphabetical, most_downloads, recently_updated, recently_created",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page num which starts from 1",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "count per page",
                        "name": "count_per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.modelsInfo"
                        }
                    }
                }
            },
            "post": {
                "description": "create model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "body of creating model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCreateModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/model/{id}": {
            "put": {
                "description": "update model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUpdateModel"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/model/{owner}": {
            "get": {
                "description": "list model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelWeb"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of model",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "whether to calculate the total",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort types: most_likes, alphabetical, most_downloads, recently_updated, recently_created",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page num which starts from 1",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "count per page",
                        "name": "count_per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.userModelsInfo"
                        }
                    }
                }
            }
        },
        "/v1/model/{owner}/{name}": {
            "get": {
                "description": "get model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelWeb"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of model",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.modelDetail"
                        }
                    }
                }
            }
        },
        "/v1/name": {
            "head": {
                "description": "Check the name is available",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Name"
                ],
                "summary": "Check the name is available",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "name"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "name"
                        }
                    }
                }
            }
        },
        "/v1/organization": {
            "get": {
                "description": "get organization info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Get all organization of the user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter by owner ",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by username",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.OrganizationDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Create organization",
                "parameters": [
                    {
                        "description": "body of new organization",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.orgCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/app.OrganizationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "not_found"
                        }
                    }
                }
            }
        },
        "/v1/organization/{name}": {
            "get": {
                "description": "get organization info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Get one organization info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.OrganizationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "put": {
                "description": "update org basic info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Update org basic info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of new organization",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.orgBasicInfoUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/app.OrganizationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "post": {
                "description": "delete a organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Leave the organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "permission"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Delete organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "permission"
                        }
                    }
                }
            }
        },
        "/v1/organization/{name}/member": {
            "get": {
                "description": "list organization members",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "List organization members",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.MemberDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "permission"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit a member to the organization's role",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Edit organization member",
                "parameters": [
                    {
                        "description": "body of new member",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.OrgMemberEditRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/app.MemberDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a member from a organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Remove organization members",
                "parameters": [
                    {
                        "description": "body of the removed member",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.orgMemberRemoveRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            }
        },
        "/v1/request": {
            "get": {
                "description": "List invitation of the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "List requests of the organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organization name",
                        "name": "org_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "invitee name",
                        "name": "requester",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "invitation status, can be: pending/approved/rejected",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page index",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.MemberRequestDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            },
            "put": {
                "description": "Approve a user's member request of the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Approve a user's member request of the organization",
                "parameters": [
                    {
                        "description": "body of the accept",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.OrgApproveMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/app.MemberRequestDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            },
            "post": {
                "description": "Request to be a member of the organization",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Request to be a member of the organization",
                "parameters": [
                    {
                        "description": "body of the member request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.OrgReqMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/app.OrganizationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "get": {
                "description": "get user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get a user info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account",
                        "name": "account",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.userDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "put": {
                "description": "update user basic info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user basic info",
                "parameters": [
                    {
                        "description": "body of updating user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.userBasicInfoUpdateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/user/check_email": {
            "get": {
                "description": "check user email",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "no"
                        }
                    }
                }
            }
        },
        "/v1/user/token": {
            "get": {
                "description": "list all platform tokens of user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.TokenDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new platform token of user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create a user token",
                "parameters": [
                    {
                        "description": "body of create token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.tokenCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "created"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            }
        },
        "/v1/user/token/{name}": {
            "delete": {
                "description": "delete a new platform token of user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete a user token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "not_found"
                        }
                    }
                }
            }
        },
        "/v2/model": {
            "get": {
                "description": "list global public model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelRestful"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of model",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "task label",
                        "name": "task",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "other labels, separate multiple each ones with commas",
                        "name": "others",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "license label",
                        "name": "license",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "framework labels, separate multiple each ones with commas",
                        "name": "frameworks",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "whether to calculate the total",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort types: most_likes, alphabetical, most_downloads, recently_updated, recently_created",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page num which starts from 1",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "count per page",
                        "name": "count_per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ModelsDTO"
                        }
                    }
                }
            }
        },
        "/v2/model/{owner}/{name}": {
            "get": {
                "description": "get model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelRestful"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of model",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ModelDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ApproveDTO": {
            "type": "object",
            "properties": {
                "by": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "inviter": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "app.MemberDTO": {
            "type": "object",
            "properties": {
                "org_full_name": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "app.MemberRequestDTO": {
            "type": "object",
            "properties": {
                "by": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "app.ModelDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "labels": {
                    "$ref": "#/definitions/app.ModelLabelsDTO"
                },
                "like_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "app.ModelLabelsDTO": {
            "type": "object",
            "properties": {
                "frameworks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "license": {
                    "type": "string"
                },
                "others": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "task": {
                    "type": "string"
                }
            }
        },
        "app.ModelsDTO": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.ModelSummary"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "app.OrganizationDTO": {
            "type": "object",
            "properties": {
                "allow_request": {
                    "type": "boolean"
                },
                "avatar_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "default_role": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "platform_id": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "app.TokenDTO": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "expired": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "controller.OrgAcceptMemberRequest": {
            "type": "object",
            "required": [
                "org_name"
            ],
            "properties": {
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                }
            }
        },
        "controller.OrgApproveMemberRequest": {
            "type": "object",
            "required": [
                "org_name"
            ],
            "properties": {
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.OrgInviteMemberRequest": {
            "type": "object",
            "required": [
                "org_name",
                "role",
                "user"
            ],
            "properties": {
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.OrgMemberEditRequest": {
            "type": "object",
            "required": [
                "role",
                "user"
            ],
            "properties": {
                "role": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.OrgReqMemberRequest": {
            "type": "object",
            "required": [
                "org_name"
            ],
            "properties": {
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                }
            }
        },
        "controller.OrgRevokeInviteRequest": {
            "type": "object",
            "required": [
                "org_name"
            ],
            "properties": {
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.OrgRevokeMemberReqRequest": {
            "type": "object",
            "required": [
                "org_name"
            ],
            "properties": {
                "msg": {
                    "type": "string"
                },
                "org_name": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.User": {
            "type": "object",
            "properties": {
                "allow_request": {
                    "type": "boolean"
                },
                "avatar_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "default_role": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "controller.modelDetail": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "labels": {
                    "$ref": "#/definitions/app.ModelLabelsDTO"
                },
                "like_count": {
                    "type": "integer"
                },
                "liked": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "controller.modelInfo": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "like_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "task": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "controller.modelsInfo": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.modelInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "controller.orgBasicInfoUpdateRequest": {
            "type": "object",
            "properties": {
                "allow_request": {
                    "type": "boolean"
                },
                "avatar_id": {
                    "type": "string"
                },
                "default_role": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "controller.orgCreateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "controller.orgMemberRemoveRequest": {
            "type": "object",
            "required": [
                "user"
            ],
            "properties": {
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.reqToCreateModel": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "init_readme": {
                    "type": "boolean"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "controller.reqToUpdateModel": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "controller.tokenCreateRequest": {
            "type": "object",
            "required": [
                "name",
                "perm"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "perm": {
                    "type": "string"
                }
            }
        },
        "controller.userBasicInfoUpdateRequest": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                }
            }
        },
        "controller.userDetail": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "controller.userModelsInfo": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.ModelSummary"
                    }
                },
                "owner": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_openmerlin_merlin-server_user_app.UserDTO": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "repository.ModelSummary": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "like_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "task": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "session.SessionDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "info": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
