// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplateinternal = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/coderepo/permission/read": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "check if can read repo's sub-resource not the repo itsself",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Read",
                "parameters": [
                    {
                        "description": "body of request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCheckPermission"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/coderepo/permission/update": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "check if can create/update/delete repo's sub-resource not the repo itsself",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "description": "body of request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCheckPermission"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/model/{id}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get model info by id",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelInternal"
                ],
                "summary": "GetById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/model/{id}/label": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "reset label of model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelInternal"
                ],
                "summary": "ResetLabel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCreateModel"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/session/check": {
            "put": {
                "description": "check and refresh session",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SessionInternal"
                ],
                "summary": "CheckAndRefresh",
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/v1/session/clear": {
            "delete": {
                "description": "Clear session when it expired",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SessionInternal"
                ],
                "summary": "Clear session by session id",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/space-app/": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "create space app",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "body of creating space app",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCreateSpaceApp"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space-app/build/done": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "notidy space app build is done",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "NotifyBuildIsDone",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToSetBuildIsDone"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space-app/build/started": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "notidy space app building is started",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "NotifyBuildIsStarted",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUpdateBuildInfo"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space-app/service/started": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "notidy space app service is started",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "NotifyServiceIsStarted",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUpdateServiceInfo"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space-app/{owner}/{name}/restart": {
            "post": {
                "description": "restart space app",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "Post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of space",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of space",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space/{id}": {
            "get": {
                "description": "get space",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space/{id}/model": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update space models relations",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "UpdateSpaceModels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ModeIds"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/user/token/verify": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "verify a platform token of user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "UserInternal"
                ],
                "summary": "Verify token",
                "parameters": [
                    {
                        "description": "body of token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.tokenVerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "token"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "token"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "token"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "internal"
                        }
                    }
                }
            }
        },
        "/v1/user/{name}/platform": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "Get platform user info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "UserInternal"
                ],
                "summary": "GetPlatformUser info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of the user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ModeIds": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controller.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.reqToCheckPermission": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.reqToCreateModel": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "init_readme": {
                    "type": "boolean"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "controller.reqToCreateSpaceApp": {
            "type": "object",
            "properties": {
                "commit_id": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "controller.reqToSetBuildIsDone": {
            "type": "object",
            "properties": {
                "commit_id": {
                    "type": "string"
                },
                "logs": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "controller.reqToUpdateBuildInfo": {
            "type": "object",
            "properties": {
                "commit_id": {
                    "type": "string"
                },
                "log_url": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "controller.reqToUpdateServiceInfo": {
            "type": "object",
            "properties": {
                "app_url": {
                    "type": "string"
                },
                "commit_id": {
                    "type": "string"
                },
                "log_url": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "controller.tokenVerifyRequest": {
            "type": "object",
            "required": [
                "action",
                "token"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and api Bearer.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "Internal": {
            "description": "Type \"Internal\" followed by a space and internal token.",
            "type": "apiKey",
            "name": "TOKEN",
            "in": "header"
        }
    }
}`

// SwaggerInfointernal holds exported Swagger Info so clients can modify it
var SwaggerInfointernal = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "internal",
	SwaggerTemplate:  docTemplateinternal,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfointernal.InstanceName(), SwaggerInfointernal)
}
