definitions:
  controller.ModeIds:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
  controller.ResponseData:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
    type: object
  controller.reqToCheckPermission:
    properties:
      name:
        type: string
      owner:
        type: string
      user:
        type: string
    type: object
  controller.reqToCreateModel:
    properties:
      desc:
        type: string
      fullname:
        type: string
      init_readme:
        type: boolean
      license:
        type: string
      name:
        type: string
      owner:
        type: string
      visibility:
        type: string
    type: object
  controller.reqToCreateSpaceApp:
    properties:
      commit_id:
        type: string
      space_id:
        type: string
    type: object
  controller.reqToSetBuildIsDone:
    properties:
      commit_id:
        type: string
      logs:
        type: string
      space_id:
        type: string
      success:
        type: boolean
    type: object
  controller.reqToUpdateBuildInfo:
    properties:
      commit_id:
        type: string
      log_url:
        type: string
      space_id:
        type: string
    type: object
  controller.reqToUpdateServiceInfo:
    properties:
      app_url:
        type: string
      commit_id:
        type: string
      log_url:
        type: string
      space_id:
        type: string
    type: object
  controller.tokenVerifyRequest:
    properties:
      action:
        type: string
      token:
        type: string
    required:
    - action
    - token
    type: object
info:
  contact: {}
paths:
  /v1/coderepo/permission/read:
    post:
      consumes:
      - application/json
      description: check if can read repo's sub-resource not the repo itsself
      parameters:
      - description: body of request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToCheckPermission'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: Read
      tags:
      - Permission
  /v1/coderepo/permission/update:
    post:
      consumes:
      - application/json
      description: check if can create/update/delete repo's sub-resource not the repo
        itsself
      parameters:
      - description: body of request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToCheckPermission'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: Update
      tags:
      - Permission
  /v1/model/{id}:
    get:
      consumes:
      - application/json
      description: get model info by id
      parameters:
      - description: id of model
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: GetById
      tags:
      - ModelInternal
  /v1/model/{id}/label:
    put:
      consumes:
      - application/json
      description: reset label of model
      parameters:
      - description: id of model
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToCreateModel'
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: ResetLabel
      tags:
      - ModelInternal
  /v1/session/check:
    put:
      consumes:
      - application/json
      description: check and refresh session
      responses:
        "202":
          description: Accepted
      summary: CheckAndRefresh
      tags:
      - SessionInternal
  /v1/session/clear:
    delete:
      consumes:
      - application/json
      description: Clear session when it expired
      responses:
        "204":
          description: No Content
      summary: Clear session by session id
      tags:
      - SessionInternal
  /v1/space-app/:
    post:
      consumes:
      - application/json
      description: create space app
      parameters:
      - description: body of creating space app
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToCreateSpaceApp'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Bearer: []
      summary: Create
      tags:
      - SpaceApp
  /v1/space-app/{owner}/{name}/restart:
    post:
      consumes:
      - application/json
      description: restart space app
      parameters:
      - description: owner of space
        in: path
        name: owner
        required: true
        type: string
      - description: name of space
        in: path
        name: name
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: Post
      tags:
      - SpaceApp
  /v1/space-app/build/done:
    put:
      consumes:
      - application/json
      description: notidy space app build is done
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToSetBuildIsDone'
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Bearer: []
      summary: NotifyBuildIsDone
      tags:
      - SpaceApp
  /v1/space-app/build/started:
    put:
      consumes:
      - application/json
      description: notidy space app building is started
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToUpdateBuildInfo'
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Bearer: []
      summary: NotifyBuildIsStarted
      tags:
      - SpaceApp
  /v1/space-app/service/started:
    put:
      consumes:
      - application/json
      description: notidy space app service is started
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToUpdateServiceInfo'
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Bearer: []
      summary: NotifyServiceIsStarted
      tags:
      - SpaceApp
  /v1/space/{id}:
    get:
      consumes:
      - application/json
      description: get space
      parameters:
      - description: id of space
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: Get
      tags:
      - SpaceInternal
  /v1/space/{id}/model:
    put:
      consumes:
      - application/json
      description: update space models relations
      parameters:
      - description: id of space
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.ModeIds'
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: UpdateSpaceModels
      tags:
      - SpaceInternal
  /v1/user/{name}/platform:
    get:
      consumes:
      - application/json
      description: Get platform user info
      parameters:
      - description: name of the user
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: GetPlatformUser info
      tags:
      - UserInternal
  /v1/user/token/verify:
    post:
      consumes:
      - application/json
      description: verify a platform token of user
      parameters:
      - description: body of token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.tokenVerifyRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: Bad Request
          schema:
            type: token
        "401":
          description: Unauthorized
          schema:
            type: token
        "403":
          description: Forbidden
          schema:
            type: token
        "500":
          description: Internal Server Error
          schema:
            type: internal
      security:
      - Internal: []
      summary: Verify token
      tags:
      - UserInternal
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and api Bearer.
    in: header
    name: Authorization
    type: apiKey
  Internal:
    description: Type "Internal" followed by a space and internal token.
    in: header
    name: TOKEN
    type: apiKey
swagger: "2.0"
