/*
Copyright (c) Huawei Technologies Co., Ltd. 2023-2024. All rights reserved
*/

// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplateinternal = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/activity": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "add activities to DB",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ActivityInternal"
                ],
                "summary": "AddActivity",
                "parameters": [
                    {
                        "description": "body of create activity app",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/activityapp.ReqToCreateActivity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {},
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "delete all the record of an resource in the DB",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ActivityInternal"
                ],
                "summary": "DeleteActivity",
                "parameters": [
                    {
                        "description": "body of delete activity app",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/activityapp.ReqToDeleteActivity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {},
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/coderepo/permission/read": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "check if can read repo's sub-resource not the repo itsself",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Read",
                "parameters": [
                    {
                        "description": "body of request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCheckPermission"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                },
                "x-example": {
                    "data": "successfully"
                }
            }
        },
        "/v1/coderepo/permission/update": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "check if can create/update/delete repo's sub-resource not the repo itsself",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "description": "body of request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCheckPermission"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                },
                "x-example": {
                    "data": "successfully"
                }
            }
        },
        "/v1/coderepo/{id}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "Get coderepo info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "CodeRepoInternal"
                ],
                "summary": "Get coderepo info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of coderepo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/coderepo/{id}/statistic/download": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update the download count of a model/space",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "CodeRepoInternal"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of model/space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating model/space info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.repoStatistics"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/coderepo/{id}/statistic/visit": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update the visit count of a space",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "CodeRepoInternal"
                ],
                "summary": "UpdateVisitCount",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating space info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.repoVisitCount"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/computility/account": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "user joined computility org",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ComputilityInternal"
                ],
                "summary": "ComputilityUserJoin",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUserOrgOperate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {},
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/computility/account/remove": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "user removed from computility org",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ComputilityInternal"
                ],
                "summary": "ComputilityUserRemove",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUserOrgOperate"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/app.AccountRecordlDTO"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {},
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/computility/org/delete": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "delete computility org",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ComputilityInternal"
                ],
                "summary": "ComputilityOrgDelete",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToOrgDelete"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/app.AccountRecordlDTO"
                                            }
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {},
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/dataset/{id}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get dataset info by id",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "DatasetInternal"
                ],
                "summary": "GetById",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of dataset",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/app.DatasetDTO"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update dataset info by id",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "DatasetInternal"
                ],
                "summary": "Update dataset info",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of dataset",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating dataset info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.datasetStatistics"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/dataset/{id}/label": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "reset label of datasets",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "DatasetInternal"
                ],
                "summary": "ResetLabel",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of dataset",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToResetDatasetLabel"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/model/relation/{id}/space": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get all spaces related to a model, including those that have been disabled.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelInternal"
                ],
                "summary": "GetSpacesByModelId",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/app.SpaceIdModelDTO"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/model/{id}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get model info by id",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelInternal"
                ],
                "summary": "GetById",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/app.ModelDTO"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update model info by id",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelInternal"
                ],
                "summary": "Update model info",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating model info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.modelStatistics"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/model/{id}/label": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "reset label of model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelInternal"
                ],
                "summary": "ResetLabel",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_openmerlin_merlin-server_models_controller.reqToResetLabel"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/model/{id}/use_in_openmind": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update space use in openmind info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ModelInternal"
                ],
                "summary": "UpdateUseInOpenmind",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "use in openmind info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/session/check": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "check and refresh session",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SessionInternal"
                ],
                "summary": "CheckAndRefresh",
                "parameters": [
                    {
                        "description": "body of new member",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.RequestToCheckAndRefresh"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/session.ResponseToCheckAndRefresh"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/session/clear": {
            "delete": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "Clear session when it expired",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SessionInternal"
                ],
                "summary": "Clear session by session id",
                "parameters": [
                    {
                        "description": "body of new member",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.RequestToClear"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space-app/": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "create space app",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "body of creating space app",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToCreateSpaceApp"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                },
                "x-example": {
                    "data": "successfully"
                }
            }
        },
        "/v1/space-app/building": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "notify space app building is started",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "NotifySpaceAppBuilding",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUpdateBuildInfo"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space-app/failed_status": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "notify space app failed status",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "NotifySpaceAppFailedStatus",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToFailedStatus"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space-app/pause": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "pause space app",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "Post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of space",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of space",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space-app/serving": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "notify space app service is started",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "NotifySpaceAppServing",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUpdateServiceInfo"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space-app/sleep": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "sleep space app",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "Post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of space",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of space",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/space-app/starting": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "notify space app build is starting",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceApp"
                ],
                "summary": "NotifySpaceAppStarting",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToNotifyStarting"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space/{id}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get space",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/app.SpaceMetaDTO1"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space/{id}/disable": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "disable space",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "Disable space",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space/{id}/label": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "reset label of space",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "ResetLabel",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_openmerlin_merlin-server_space_controller.reqToResetLabel"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space/{id}/local_cmd": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update space local cmd",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "UpdateSpaceLocalCmd",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "local cmd to reproduce the space",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space/{id}/local_env_info": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update space local env info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "UpdateSpaceLocalEnvInfo",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "local env info to update local space env info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space/{id}/model": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update space models relations",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "UpdateSpaceModels",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ModeIds"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/space/{id}/notify_update_code": {
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "NotifyIsNoApplicationFile space",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SpaceInternal"
                ],
                "summary": "NotifyIsNoApplicationFile space",
                "parameters": [
                    {
                        "maxLength": 20,
                        "type": "string",
                        "description": "id of space",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToNotifyUpdateCode"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/token/verify": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "verify a platform token of user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "UserInternal"
                ],
                "summary": "Verify token",
                "parameters": [
                    {
                        "description": "body of token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.tokenVerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/controller.tokenVerifyResp"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "token"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "token"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "token"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "internal"
                        }
                    }
                }
            }
        },
        "/v1/user/{name}/avatar_id": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get user's avatar id",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "UserInternal"
                ],
                "summary": "get user's avatar id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of the user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "$ref": "#/definitions/app.AvatarDTO"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/{name}/platform": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "Get platform user info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "UserInternal"
                ],
                "summary": "GetPlatformUser info",
                "parameters": [
                    {
                        "maxLength": 40,
                        "type": "string",
                        "description": "name of the user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "string"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "activityapp.ReqToCreateActivity": {
            "type": "object",
            "properties": {
                "owner": {
                    "type": "string"
                },
                "resource_index": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "activityapp.ReqToDeleteActivity": {
            "type": "object",
            "properties": {
                "resource_index": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                }
            }
        },
        "app.AccountRecordlDTO": {
            "type": "object",
            "properties": {
                "compute_type": {
                    "type": "string"
                },
                "quota_count": {
                    "type": "integer"
                },
                "space_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "app.AvatarDTO": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "app.DatasetDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "disable": {
                    "type": "boolean"
                },
                "disable_reason": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "labels": {
                    "$ref": "#/definitions/app.DatasetLabelsDTO"
                },
                "like_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "app.DatasetLabelsDTO": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "license": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "size": {
                    "type": "string"
                },
                "task": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "app.ModelDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "disable": {
                    "type": "boolean"
                },
                "disable_reason": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "labels": {
                    "$ref": "#/definitions/app.ModelLabelsDTO"
                },
                "like_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "usage": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "app.ModelLabelsDTO": {
            "type": "object",
            "properties": {
                "frameworks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hardwares": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "library_name": {
                    "type": "string"
                },
                "license": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "others": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "task": {
                    "type": "string"
                }
            }
        },
        "app.SpaceIdModelDTO": {
            "type": "object",
            "properties": {
                "space_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "app.SpaceMetaDTO1": {
            "type": "object",
            "properties": {
                "base_image": {
                    "type": "string"
                },
                "disable": {
                    "type": "boolean"
                },
                "hardware": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "sdk": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "controller.ModeIds": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controller.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.datasetStatistics": {
            "type": "object",
            "properties": {
                "download_count": {
                    "type": "integer"
                }
            }
        },
        "controller.modelStatistics": {
            "type": "object",
            "properties": {
                "download_count": {
                    "type": "integer"
                }
            }
        },
        "controller.repoStatistics": {
            "type": "object",
            "properties": {
                "download_count": {
                    "type": "integer"
                }
            }
        },
        "controller.repoVisitCount": {
            "type": "object",
            "properties": {
                "visit_count": {
                    "type": "integer"
                }
            }
        },
        "controller.reqToCheckPermission": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "controller.reqToCreateSpaceApp": {
            "type": "object",
            "properties": {
                "commit_id": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "controller.reqToFailedStatus": {
            "type": "object",
            "properties": {
                "all_build_log": {
                    "type": "string"
                },
                "commit_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controller.reqToNotifyStarting": {
            "type": "object",
            "properties": {
                "all_build_log": {
                    "type": "string"
                },
                "commit_id": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "controller.reqToNotifyUpdateCode": {
            "type": "object",
            "properties": {
                "commit_id": {
                    "type": "string"
                },
                "sdk_type": {
                    "type": "string"
                }
            }
        },
        "controller.reqToOrgDelete": {
            "type": "object",
            "properties": {
                "org_name": {
                    "type": "string"
                }
            }
        },
        "controller.reqToResetDatasetLabel": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "licenses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "size": {
                    "type": "string"
                },
                "task": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controller.reqToUpdateBuildInfo": {
            "type": "object",
            "properties": {
                "commit_id": {
                    "type": "string"
                },
                "log_url": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "controller.reqToUpdateServiceInfo": {
            "type": "object",
            "properties": {
                "app_url": {
                    "type": "string"
                },
                "commit_id": {
                    "type": "string"
                },
                "log_url": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "controller.reqToUserOrgOperate": {
            "type": "object",
            "properties": {
                "org_name": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "controller.tokenVerifyRequest": {
            "type": "object",
            "required": [
                "action",
                "token"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "controller.tokenVerifyResp": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                }
            }
        },
        "github_com_openmerlin_merlin-server_models_controller.reqToResetLabel": {
            "type": "object",
            "properties": {
                "frameworks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hardwares": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "libraryName": {
                    "type": "string"
                },
                "licenses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "task": {
                    "type": "string"
                }
            }
        },
        "github_com_openmerlin_merlin-server_space_controller.reqToResetLabel": {
            "type": "object",
            "properties": {
                "licenses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "task": {
                    "type": "string"
                }
            }
        },
        "session.RequestToCheckAndRefresh": {
            "type": "object",
            "properties": {
                "csrf_token": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "session.RequestToClear": {
            "type": "object",
            "properties": {
                "session_id": {
                    "type": "string"
                }
            }
        },
        "session.ResponseToCheckAndRefresh": {
            "type": "object",
            "properties": {
                "csrf_token": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and api Bearer.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "Internal": {
            "description": "Type \"Internal\" followed by a space and internal token.",
            "type": "apiKey",
            "name": "TOKEN",
            "in": "header"
        }
    }
}`

// SwaggerInfointernal holds exported Swagger Info so clients can modify it
var SwaggerInfointernal = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "internal",
	SwaggerTemplate:  docTemplateinternal,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfointernal.InstanceName(), SwaggerInfointernal)
}
