name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
      - run: go test -v -coverprofile=profile.cov ./...
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: modelfoundry:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max