name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
env:
  GOPRIVATE: "github.com/openmerlin"

jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'
      - name: config private models
        env:
          TOKEN: ${{ secrets.PKKING_PERSONAL_TOKEN }}
        run: git config --global url."https://pkking:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Install Dependencies
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Unit tests
        run: go test -race -count=1 -v ./...
      - name: Run Gosec Security Scanner
        run: docker run --rm -i -w /data -v `pwd`:/data securego/gosec -exclude-dir api -exclude-dir tests ./...
      - name: Run e2e tests
        run: bash -x scripts/init-env.sh && bash -x scripts/openapi.sh && cd tests/e2e && go test -v -count=1 ./...
      - name: Self Hosted Runner Post Job Cleanup Action
        uses: TooMuch4U/actions-clean@master